### PR TITLE
PKCS#7 implementation of pad/2 and depad/1

### PR DESCRIPTION
**Pull request by ghost**
I really appreciate your library and have been using it, but came across a bug where trailing whitespace will be truncated. If you could take a look and let me know your thoughts, I used the Wikipedia entry for [PKCS#7](https://en.wikipedia.org/wiki/Padding_(cryptography)#PKCS7) as a guide for implementation. I wrote a test that proves the whitespace issue as well. 

pad/2 and depad/1 as revised adhere closer to the PKCS#7 implementation described in RFC 5652, where the value of each padding byte is the number of bytes that were added as padding, which prevents any trailing character with a matching byte value from being truncated by depad.

Since the old code used the space as the padding, which is value << 32 >>, this code would truncate the last 32 bytes of an encrypted message. There could be a legacy check that looks for if the last byte of the data passed to depad/1 is 32 and it could use the old behavior.

### CODE REVIEW

**Comment by rubencaro** [comment]
Hi @AlecHansen,

This looks great! Can you please write the legacy check you mentioned? Then I can merge this without breaking things.

Thanks.

**Comment by ghost** [comment]
I had to expose pad/2 and depad/1 to write tests for whether legacy padded messages could be depadded using the new implementation, we could make them public or using @compile if Mix.env == :test, do: :export_all in the module exposes all functions when tests are run. I'm not sure if this will emit a warning in a user's project when the run mix test, however. Let me know what your thoughts are on this, making the functions public might be a bad choice because it was much easier for me to know that pad and depad were only being used in the cipher module.
There is a perfectly legitimate time that << 32 >> can be the end block, when the block size is set greater than or equal to 32 and the pad needs to be 32 bytes in length. 
So if someone was previously using a block_size of 32 or greater and counting on whitespace at the end of their message (which seems unlikely as it was truncated before) the behavior might change slightly where the whitespace gets truncated, but it won't truncate any non-whitespace part of the message now. 
The logic wouldn't be as complicated if pad/2 was simple pad/1 and the block_size was static at 16, which is how it's being used, because at that point there would never be a legitimate time that the end of the string would be a space, so we'd know right away it was a legacy pad and could use the legacy behavior. But I'm not sure you'd want to change that to be static, and am not encouraging you to do so. 
Anyway, let me know what you think.

**Comment by rubencaro** [comment]
Yeah, absolutely. Go on making pad/1 by forcing block_size to 16. There's no real need for that to be dynamic anyway, and that would definitely simplify this case.

Nice trick with the `@compile`! I have no problem using it for this case, because this is quite simple, and will stay like this. This library is meant to cover a pretty particular case for me where I could not use JWT. For more complex cases I strongly recommend _a good implementation_ of the JWT standard.

Great job @AlecHansen !

I will happily merge this.

**Comment by ghost** [comment]
Ok, I made the changes, which let me greatly simplify the code. If our use case gets any more complicated I'll check out using JWT, thanks for the feedback and the kind words, @rubencaro

**Pull request merged**
